name: Update Cards Price Scheduled Job
on:
  push:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.5.1
      - name: Install dependencies
        run: yarn install
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
      - name: Run updateCardsJson.js script
        run: node script/updateCardsJson.js
      - name: Run insertCardsJsonToDb.js script
        run: node script/insertCardsJsonToDb.js
